#!/bin/bash
cd downloads/cv
pdflatex resume.tex;
echo -e "\n\nencoding resume.pdf with 128 bit encription now\n\n"
pdftk resume.pdf output temp.pdf user_pw semaphore;
rm resume.pdf; mv temp.pdf resume.pdf

clean

cd ../../

cd downloads/Papers
#pdftk ~/Documents/Papers/SRS/Continuum/kinecontrol/kinecontrol.pdf output kinecontrol.pdf  user_pw semaphore
cp ~/Documents/Papers/SRS/Continuum/kinecontrol/kinecontrol.pdf kinecontrol.pdf  
cp ~/Documents/Papers/SRS/Springer2019/springer19.pdf Springer19.pdf
cp ~/Documents/Papers/PhDThesis/thesis.pdf PhDThesis.pdf 
cp ~/Documents/Papers/SRS/Continuum/model/model.pdf ContinuumI.pdf

cd ../../

