#!/bin/bash
cd downloads/cv
pdflatex resume.tex;
echo -e "\n\nencoding resume.pdf with 128 bit encription now\n\n"
pdftk resume.pdf output temp.pdf user_pw semaphore;
rm resume.pdf; mv temp.pdf resume.pdf

clean

cd ../../
